### ISSUE TITLE
http://localhost:32123/ could not connect

### ISSUE THREAD

**Issue by Gildesh** [google/mesop#1003]
I followed the basic instructions on both the colab and the local machine but in both cases got this error when I actually went to this url
http://localhost:32123/
or for that matter
http://localhost:32123/hello_world

**Comment by richard-to** [comment]
I tried it out on Colab and it seems fine to me.

Can you try running this notebook in colab -> https://github.com/google/mesop/blob/main/notebooks/mesop_colab_getting_started.ipynb?

Just click the "Open in Colab" button. Then run all the cells.

**Comment by Gildesh** [comment]
colab_show works but if i manually copy the url
http://localhost:32123/hello_world, and paste it on my chrome browser, it doesn't work

**Comment by richard-to** [comment]
Yes, that is expected behavior. Colab is running from a different server. It does not run locally. That's why the localhost url does not work.

In order to get Mesop running on your local computer, you need to run the mesop code on your computer.

See https://google.github.io/mesop/getting-started/quickstart/

For https://google.github.io/mesop/getting-started/installing/, you will need to follow option B for using the command line.

Maybe the docs could be clearer that colab does not run locally.

**Comment by richard-to** [comment]
I have not used pipenv before. What's the specific error message you are getting when you use pipenv?

**Comment by Gildesh** [comment]
localhost could not connect.
That's strange because in your tutorials you have mentioned virutalenv. which works similar to a pipenv

**Comment by wwwillchen** [comment]
Can you try creating a virtualenv directly without pipenv and see if that works? I'm not familiar with pipenv but given that pip install works, I'm inclined to think something is broken with your pipenv setup (and you could try reinstalling that).
