### ISSUE TITLE
Sidenav on esc close menu

### ISSUE THREAD

**Issue by goran-markovic85** [google/mesop#1019]
**Describe the bug**
Sidenav is closing when you press ESC key. The state of sidenav_open is not change instead only css class .mat-drawer transform: translate3d(-100%, 0, 0); 

**To Reproduce**
Click on Sidenav then press ESC key

**Expected behavior**
Sidenav should have option to not close sidenav or to change state with ESC.

**Desktop System Info**

- OS: Mac, Ubuntu 24.04
- Browser Chrome, Firefox
- Version latest

**Comment by richard-to** [comment]
Good catch. Thanks for bringing this to our attention. Seems like it should be a quick fix, so I'll see if I can look at it this week.

**Comment by richard-to** [comment]
I looked at the sidenav API. Seems it should be easy to add both options. And I think API-wise it seems fairly clear.

We can use the `openChanged` event to notify the Mesop app when the state of the side nav has changed. In this case it would be up to user to update the closed state accordingly.

We can also use the `disableClose` to make it so that pressing ESC and clicking the background will not close the sidenav.
