### ISSUE TITLE
File download Component

### ISSUE THREAD

**Issue by raphsaeed** [google/mesop#1029]
Hello,
I am heavy python and c++ code behind the scenes where file down load by a user is critical. 
Please would it be possible to do this as we already have with file upload.

Thanks and Regads
Raphael

**Comment by richard-to** [comment]
Yes, this is a somewhat common request. Here is a related issue: https://github.com/google/mesop/issues/998

I'm going to close this one. Feel free to give a +1 (thumbs up) to that issue and your comments to that issue, so we can get more of a sense of the demand for this feature.

It's something I've been thinking about in terms of how to approach the implementation, since I have a use case where I would like to allow downloads as well.
