### ISSUE TITLE
Card and Expansion_panel not working

### ISSUE THREAD

**Issue by ml2s** [google/mesop#1098]
Seems neither Card nor Expansion_panel has been added successfully.

When running card.py from demo, I got: module 'mesop' has no attribute 'card'

BTW, I have updated mesop to 0.12.8.

![Image](https://github.com/user-attachments/assets/3bccc1d4-21be-49e8-960f-f073015e72f3)

**Comment by richard-to** [comment]
This is due to Card and Expansion Panel not being in the current latest Mesop pip release. The components should be available in the next release.

It's just a big confusing since the docs are synced to main rather than the pip release. And also if you pull the repo, the only way to use the latest code is run Mesop with Bazel (instead of a via pip).

**Comment by ml2s** [comment]
Thanks for clarification. Looking forward to the next release.

**Comment by wwwillchen** [comment]
We just published a new release [v0.12.9](https://github.com/google/mesop/releases/tag/v0.12.9) - thanks for waiting.
