### ISSUE TITLE
Provide a copy to clipboard command

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#224]
This puts text into a clipboard:

`me.copy_to_clipboard(text)`

Potentially want the corresponding API of reading from a clipboard but that requires browser permission

**Comment by ChaitanyaYeole02** [comment]
Hey, can you assign this issue to me?

**Comment by tpcgold** [comment]
There are solutions for this. I currently have a workaround like this implemented: 
in main.py:
 ```
 from copy_to_clipboard import copy_to_clipboard
 
 def on_click_clipboard():
 state = me.state(State)
 copy_to_clipboard(value=state.output)
 ```
in copy_to_clipboard.py:
```
from typing import Any, Callable

import mesop.labs as mel
from mesop.events import ClickEvent


@mel.web_component(path="copy_to_clipboard.js")
def copy_to_clipboard(
    *,
    value: str,
    on_copy: Callable[[str], Any] = None,  # Type hint for on_copy argument
    key: str | None = None,
):
    async def _on_copy(event: ClickEvent):
        return

    return mel.insert_web_component(
        name="clipboard-component",
        key=key,
        events={
            "click": _on_copy,  # Directly bind the click event to the handler
        },
        properties={
            "value": value,
        },
    )

```
in copy_to_clipboard.js
```
import {html, LitElement} from 'https://cdn.jsdelivr.net/gh/lit/dist@3/core/lit-core.min.js';

class ClipboardComponent extends LitElement {
    static properties = {
        value: {type: String},
        copyEvent: {type: String},
    };

    constructor() {
        super();
        this.value = "";
        this.copyEvent = "";
    }

    connectedCallback() {
        super.connectedCallback();
        this.addEventListener("click", this._onCopy);
    }

    disconnectedCallback() {
        super.disconnectedCallback();
        this.removeEventListener("click", this._onCopy);
    }

    render() {
        return html`
            <div class="container">
                <button @click="${this._onCopy}">
                    Copy to Clipboard
                </button>
            </div>
        `;
    }

    async _onCopy() {
        const textToCopy = this.value;
        try {
            await navigator.clipboard.writeText(textToCopy);
            console.log("Text copied to clipboard!");
            this.dispatchEvent(
                new MesopEvent(this.copyEvent, {
                    value: textToCopy,
                })
            );
        } catch (err) {
            console.error("Failed to copy text:", err);
        }
    }
}

customElements.define('clipboard-component', ClipboardComponent);
```

but i haven't found a way to use the button class of mesop so it's just an ugly html button and the event handler is calling a python function that is empty. 

great thing is it works to pass the state.output to the clipboard this way.

**Comment by richard-to** [comment]
^I think with a web component, there's a way to use slots().

See https://github.com/google/mesop/blob/main/mesop/examples/web_component/slot/slot_app.py

Haven't tried it yet, but I think with the slots you could have something like:

```
with copy_to_clipboard(...):
  me.button("Copy to clipboard")

with copy_to_clipboard(...):
  me.text("Some text to copy to clipboard if clicked on")
```

In this scenario, I think the user would click on the button or the text and it would copy via the click event on the outer copy_to_clipboard web component.

So maybe that is a way to use the built in components in this case.

-----

I do agree that being able to use custom Javascript in built-in components could be nice. There are some Angular Components that we can't create a Mesop version for, such as Dialog due to how they depend on Angular components or ng template.

Or in the case me.table, there are things like dynamic cell styling based on the content that is hard to do nicely without being able to add some javascript code.

I think the main question there is how to allow those kinds of javascript extensions in a good, user-friendly, clean, and extensible way.

**Comment by richard-to** [comment]
Tested the copy to clipboard functionality out real quick using the command approach. Works on Chrome, Firefox but not Safari.

I think the command approach isn't being counted as a button click (or user interaction), so they copy seems blocked in this scenario.

**Comment by richard-to** [comment]
Here's a pull request that illustrates my suggestion to use a web component with slots. This way you can use core Mesop components to take the button (https://github.com/google/mesop/pull/720).

**Comment by wwwillchen** [comment]
Closing in favor of the web component approach - see #720
