### ISSUE TITLE
Unable to load the mesop app in my browser 

### ISSUE THREAD

**Issue by abhishek085** [google/mesop#441]
Bug: Unable to load the Mesop App in my browser . It is stuck as Loading in the window.

Using VScode run the below simple hello_world.py from the mesop sample.
import mesop as me

@me.page()
def app():
  me.text("Hello World")

**Screenshots**
![image](https://github.com/google/mesop/assets/23297408/37927d13-e11b-48c8-95d8-e607932ae8d4)

**Desktop System Info**

- OS: Windows
- Browser : Chrome, Edge

The app is running and hot reloading and everything works fine. I am not able to load the UI in the browser.

**Comment by wwwillchen** [comment]
Can you open Chrome DevTools and paste your console log messages, especially any errors?

**Comment by abhishek085** [comment]
Getting these two errors:
Refused to execute script from 'http://localhost:32123/zone.js/bundles/zone.umd.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

maybe due to : web server isn't correctly identifying the zone.umd.js file as a JavaScript file

**Comment by wwwillchen** [comment]
Looks like a similar issue as #463. Could you follow the steps in https://github.com/google/mesop/issues/463#issuecomment-2176531883 and let me know what you get? Thanks.

**Comment by wwwillchen** [comment]
Also, just checking how are you installing Mesop? If you're not using a virtual environment, please follow these steps: https://google.github.io/mesop/getting_started/installing/#create-a-venv-environment

**Comment by gamesbyjames** [comment]
same issue, follows the venv instructions from the getting started guide. Just see "Loading..." with these errors in the browser console:

The resource from “http://localhost:32123/zone.js/bundles/zone.umd.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'self' 'nonce-...'”
The resource from “http://localhost:32123/zone.js/bundles/zone.umd.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
Loading failed for the <script> with source “http://localhost:32123/zone.js/bundles/zone.umd.js”.
Loading module from “http://localhost:32123/editor_bundle/bundle.js” was blocked because of a disallowed MIME type (“text/plain”).
Loading failed for the module with source “http://localhost:32123/editor_bundle/bundle.js”

**Comment by GTimothee** [comment]
seems like a flask issue https://stackoverflow.com/questions/59355194/python-flask-error-failed-to-load-module-script-strict-mime-type-checking-i

**Comment by wwwillchen** [comment]
Thanks @GTimothee for the pointer, I think I've fixed it in #532 and have cut a new release [v0.9.2](https://github.com/google/mesop/releases/tag/v0.9.2).

Please the latest version and let me know if it's fixed the issue : `pip install --upgrade mesop`

Thanks!

**Comment by abhishek085** [comment]
Thanks, After the update its working now.
