### ISSUE TITLE
Can we upgrade pydantic to a more recent version?

### ISSUE THREAD

**Issue by mbzuaiciao** [google/mesop#442]
I received the following error due to the fact that mesop seems to rely on a old version of pydantic. Is it possible to upgrade it to a more recent version.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mesop 0.8.0 requires pydantic==1.10.13, but you have pydantic 2.7.4 which is incompatible.

Thanks,

**Comment by wwwillchen** [comment]
Thanks for filing an issue. I'll look into upgrading Pydantic.

The main reason we pin it to 1.10.13 is because of this function: https://github.com/google/mesop/blob/e1ee74aae984e200fe755589bf2fbb6824260d6d/mesop/utils/caller.py#L6, which is needed for the visual editor (i.e. edit in Mesop dev tools and get source code edits)

@richard-to do you ever use the visual editor? I'm thinking about retiring it given this + other issues which makes it a maintenance burden. I have a strong suspicion almost no one uses it (it doesn't work with `pip install mesop` or colab, see #43

**Comment by richard-to** [comment]
Yeah, I don't think I've ever used the visual editor for actual development. I think it may be ok to retire now and we can bring back a revamped version later.

**Comment by wwwillchen** [comment]
Please use v0.9.1 - it now supports Pydantic v2 or v1.

**Comment by kizombaciao** [comment]
Thank you
