### ISSUE TITLE
The `me.markdown()` component can't render the output of `pd.DataFrame().to_markdown()`

### ISSUE THREAD

**Issue by aperepel** [google/mesop#546]
**Describe the bug**
The dataframe markdown is not recognized by the renderer, simply prints the markup (unreadable, no pre-formatting)

**To Reproduce**
```python
import pandas as pd
 
df = pd.DataFrame(
data={
    "NA": [pd.NA, pd.NA, pd.NA],
    "Index": [3, 2, 1],
    "Bools": [True, False, (True)],
    "Ints": [101, 90, -55],
    "Floats": [2.3, 4.5, -3.000000003],
    "Strings": ["Hello", "World", "!"],
    "Date Times": [
      pd.Timestamp("20180310"),
      pd.Timestamp("20230310"),
      pd.Timestamp("20230310"),
    ],
  }
)

me.markdown(df.to_markdown())
```

**Expected behavior**
Renders a visually appealing and formatted data table.

**Comment by richard-to** [comment]
This looks like a simple bug to fix.

We just need to enable the extension: https://python-markdown.github.io/extensions/tables/

Just need to add the extension here I think: https://github.com/google/mesop/blob/412cd8e21493cc5ec5656ea81592e4255483c018/mesop/components/markdown/markdown.py#L30

**Comment by richard-to** [comment]
Ok, the fix is in for the markdown formatting. The big caveat here is that the default styling of the table isn't that nice. 

There is a hacky way around this by including a [custom stylesheet](https://google.github.io/mesop/api/page/#mesop.features.page.page) and using the markdown [attr_list](https://python-markdown.github.io/extensions/attr_list/)

Just note that the custom stylesheet would need to be hosted outside of the Mesop app:

- CDN
- GCS / S3
- You could do the same server / domain if you had something like nginx to route to the files and to mesop, but that's a more advanced set up
