### ISSUE TITLE
Add Support for Additional State Session Backends

### ISSUE THREAD

**Issue by richard-to** [google/mesop#556]
Right now the state session backend feature only supports memory. Memory is not the best choice most of the time.

Completed:

- File (DONE)
- GCP Firestore (has free tier) (DONE)
- SQLAlchemy (Postgres, SQlite, etc, GCP Cloud Cloud SQL) (DONE)

Other considerations if there is interest:

- Redis (Valkey fork of Redis, GCP Memorystore)
- Memcached (GCP Memorystore)
- GCP Cloud Storage
- Other popular key/value store?

Ref: https://google.github.io/mesop/api/config/#mesop_state_session_backend

**Comment by wwwillchen** [comment]
@richard-to I think we need some kind of guide. Technically all the information is in https://google.github.io/mesop/api/config/ but it's not obvious to look there. I think having some kind of "Performance" guide would be very helpful.

Something like:
- How do I diagnose my performance problem? e.g. is it because state is too large or some other reason
- If state is a problem, how do I pick which state session backend is suitable?

**Comment by richard-to** [comment]
Going to close this for now. We can create new issues for additional backends if there is interest.
