### ISSUE TITLE
local installation not working, the mesop executable isn't copied to the Scripts directory

### ISSUE THREAD

**Issue by gamesbyjames** [google/mesop#561]
When trying a local installation, the mesop executable isn't copied to the Scripts directory

**To Reproduce**
1. create and activate a python 3.10 environment (Im using conda) 
2. clone the repo (I cloned 0.9.3)
3. cd mesop
4. pip install -e .
5. the installation is reported as successful (but note that the version in pyproject.toml is incorrect (0.0.1))
6. the mesop executable is not copied to the Scripts folder

**Expected behavior**
The mesop executable should be copied to the Scripts folder

- OS: Windows 11
- Version 0.9.3

**Comment by richard-to** [comment]
I would recommend not doing a local build. It is not straightforward to do a local build since there are a lot of extra packaging and build steps to make the executable.

You will need to do two things to make it work:

- Need to set up the Mesop internal development environment for working on the core framework
  - Instructions here https://google.github.io/mesop/internal/development/ (though you can also use Github Code Spaces or VS Code remote container for quicker set up)
- To create the local pip package you will then need to run the script here https://github.com/google/mesop/blob/main/scripts/pip.sh

Is there a reason you want to create a local installation?

**Comment by gamesbyjames** [comment]
Thanks Richard. It was to try and address questions like the one over here: [https://github.com/google/mesop/discussions/560] 

(https://github.com/google/mesop/discussions/560)

Any suggestions for that one very welcome btw :-)

**Comment by richard-to** [comment]
I see. So you want to make a custom build that can return an image in the chat interface.

One of the nice things about the Mesop chat widget is that it's written in pure Mesop code.

The source is right here: https://github.com/google/mesop/blob/main/mesop/labs/chat.py

So you can just copy that code to say your own application. So copy the code to chat.py. Then modify it.

Then in your main.py, you can import your modified chat.py to return images.

You can also look at the code in text_to_image to see how image rendering works right now in Mesop typically: https://github.com/google/mesop/blob/main/mesop/labs/text_to_image.py

We typically passing the data URL of the image. There is a drawback in that if you have a lot of images, this could make your application very slow. 

We're working on some performance improvements so that state isn't passed back and forth constantly. So you can try using the memory backend: https://google.github.io/mesop/api/config/#mesop_state_session_backend. There are some limitations to this approach though. But we're working on adding more backends (https://github.com/google/mesop/issues/556). Let me know if you have any backends of interest.

There is also a workaround of uploading the images to say Google Cloud Storage or Amazon S3 and linking to the images that get generated from there to reduce the amount of data being passed back and forth.
