### ISSUE TITLE
Chat UI Component Stops Loading - Google Colab Notebook

### ISSUE THREAD

**Issue by ellenealds** [google/mesop#571]
**Describe the bug**
The Chat UI component was working perfectly, it loaded as expected and I was able to interact with it. There were no changes or any noticable activity that would cause this.

**To Reproduce**
- Run cells in this notebook: https://colab.research.google.com/drive/1GDEXe_9Ayq0xAKnKvj4m9wjx3hJ4s-Qo?usp=sharing

**Expected behavior**
The chat UI should display like this:
![image](https://github.com/google/mesop/assets/107104287/74c3ee09-405b-473e-8f4b-f2fe56f0d83a)

**Screenshots**
![image](https://github.com/google/mesop/assets/107104287/e9aacd1e-9068-4616-aeaf-3401520a7fe7)

**Comment by ellenealds** [comment]
**Update:** I could force it to work by running 'me.colab_run()' in the notebook. 

I did not need this in my notebook before and it worked, is this expected when using the framework?

**Comment by wwwillchen** [comment]
Yeah, you need to have `colab_run` which starts the Mesop server - otherwise it won't work.

My guess is that you had executed `colab_run` previously in the notebook and (perhaps deleted the cell, but the server is still running in the background).

I think we could make this more intuitive though, by telling users that colab_run isn't running rather than silently not showing anything.
