### ISSUE TITLE
Unintentional on_input_enter trigger when confirming IME composition in chat component

### ISSUE THREAD

**Issue by kyohei3** [google/mesop#588]
**Describe the bug**

This is an issue in the chat component.

When using an IME that requires composition, such as Japanese or Chinese, the on_input_enter event is unintentionally triggered when pressing Enter to confirm the composition.

**To Reproduce**

1. Go to the [demo gallery](https://google.github.io/mesop/demo/) and open Chat demo.
2. Focus on the input element below and type something using a Japanese/Chinese IME (or any other IME that requires composition).
3. Press "Enter" to confirm the IME conversion.

**Expected behavior**

The composition should be confirmed, but the text should not be passed to the `on_input_enter` event.

**Screenshots**

**Desktop System Info**

- OS: macOS Sonoma 14.5
- Browser: Google Chrome
- Version:  126.0.6478.127（Official Build） （arm64）

**Additional context**

**Comment by richard-to** [comment]
Thanks for the catch. That's a tricky one.

As a temporary fix, you can make a copy of https://github.com/google/mesop/blob/main/mesop/labs/chat.py and remove the on enter event on line 13. This means you will only be able to send the chat input by pressing the button. But probably better than the current behavior.

Basically, copy the chat.py file to your own chat.py file. Then import your custom chat.py into your main mesop application.

**Comment by kyohei3** [comment]
@richard-to Thank you for the advice. 

I tried to change code like this, but it does not work with my environment (Mac and Chrome).

```typescript
const keyboardEvent = event as KeyboardEvent;
if (keyboardEvent.key === 'Enter' && !keyboardEvent.isComposing) {
  // ...
}
```

As far as I observed key events on my environment and read some Japanese articles, `isComposing` is set to `true` on keydown event but set to `false` on keyup event. I locally changed here to `(keydown)=...` and found it worked as expected.

https://github.com/google/mesop/blob/273c65d26f710f19504525b7295e101430f284d5/mesop/components/input/input.ng.html#L54

Do you think it makes scene to replace keyup event with keydown?

**Comment by richard-to** [comment]
Thanks for looking into this. That's very interesting to know.

Key up would be preferable since it won't fire that many events to Mesop server. If necessary, it's possible we can debounce the keydown if someone decides to hold down the enter key for whatever reason.

---------

I wonder if we can have both a key up and key down event. So the key down event would check if isComposing is True (this would be stored as a variable on the component. Then on key up we could check the stored variable.

Not sure if that will work or not. But the hope is that the first key down will log isComposing is True. Then the second key down will log isComposing is False. Can you give that a try?

**Comment by richard-to** [comment]
I added a fix for the IME issue here: https://github.com/google/mesop/pull/593 I'm not completely sure if I tested it right. I don't normally use IME, but I tested by enabling IME for Japanese on MacOS.

**Comment by richard-to** [comment]
I tested on Chrome and Firefox and the behavior was the same. However, Safari didn't work.

**Comment by richard-to** [comment]
Ok, I submitted a fix. Now just need to wait for it to reach the next Mesop release.
