### ISSUE TITLE
mel.chat gets very slow as more and more messages are added

### ISSUE THREAD

**Issue by richard-to** [google/mesop#591]
See discussion in https://github.com/google/mesop/discussions/578

**Comment by richard-to** [comment]
On the server, I think the bottle neck is the `runtime().run_path(path=path, trace_mode=trace_mode)` step in the render_loop. 

It's the one part that seems to get slower as more chat messages are added. It can also run multiple times per loop (if render_loop is called multiple times).

```
Run path took 2.07 ms
Run path took 23.95 ms
Run path took 13.17 ms
Run path took 2.33 ms
Run path took 1.28 ms
Run path took 2.89 ms
Run path took 1.78 ms
Run path took 2.02 ms
Run path took 2.12 ms
Run path took 4.20 ms
Run path took 9.52 ms
Run path took 4.86 ms
Run path took 4.06 ms
Run path took 6.63 ms
Run path took 7.76 ms
Run path took 12.51 ms
Run path took 7.59 ms
Run path took 6.71 ms
Run path took 10.55 ms
Run path took 10.56 ms
Run path took 16.05 ms
Run path took 10.56 ms
Run path took 9.18 ms
Run path took 12.23 ms
Run path took 13.28 ms
Run path took 11.30 ms
Run path took 12.44 ms
Run path took 12.19 ms
Run path took 13.89 ms
Run path took 15.27 ms
Run path took 22.88 ms
Run path took 14.18 ms
Run path took 13.72 ms
Run path took 17.43 ms
Run path took 17.63 ms
Run path took 24.96 ms
Run path took 16.84 ms
Run path took 15.55 ms
Run path took 22.88 ms
Run path took 18.88 ms
Run path took 29.28 ms
Run path took 18.47 ms
Run path took 19.85 ms
Run path took 24.90 ms
Run path took 21.01 ms
Run path took 34.92 ms
Run path took 20.80 ms
Run path took 21.60 ms
Run path took 28.37 ms
Run path took 23.13 ms
Run path took 33.91 ms
Run path took 21.84 ms
Run path took 23.68 ms
Run path took 29.98 ms
Run path took 25.43 ms
```

The other bottleneck is simply more data being sent to the server:


# Earlier example

<img width="350" alt="Screenshot 2024-07-11 at 3 29 03 PM" src="https://github.com/user-attachments/assets/a6d0f6a0-425c-4f13-98de-26c112961c90">

# Later example

<img width="352" alt="Screenshot 2024-07-11 at 3 28 53 PM" src="https://github.com/user-attachments/assets/9b66e175-a2e3-429a-a9a7-c7bed49a32c0">

I think it's interesting that the content being downloaded continues to grow larger. That seems like it could indicate undesirable behavior in the diffing algorithms (i.e. more data being sent back than should be expected). I'll look into that more later.

**Comment by richard-to** [comment]
The content downloaded section is interesting. When I looked at the response stream, it looks like the same amount of data each time (meaning the diffs are working as expected). But because we're streaming data, there's some gaps in between each response. So I think the content downloaded part covers the first message that gets generated and before that it is the debugging loop mostly likely. In both scenarios, the run path is being called.

So right now I'm thinking run_path is may be the best place to dig further.

**Comment by wwwillchen** [comment]
I did some profiling with a modified chat demo: https://github.com/google/mesop/pull/612

Here's some analysis in colab:
https://colab.research.google.com/drive/1RENgZzY-Z7wbPQ0Zg8b4z58jdyHaRPwR?usp=sharing

Here's the summary table (sorted by tottime):

|index|ncalls|tottime|percall|cumtime|percall|filename:lineno\(function\)|
|---|---|---|---|---|---|---|
|483|1|0\.152|0\.152|0\.152|0\.152|\{built-in method time\.sleep\}|
|415|4192|0\.087|0\.000|0\.089|0\.000|treeprocessors\.py:253\(\_\_applyPattern\)|
|538|1834|0\.039|0\.000|0\.039|0\.000|\{method 'search' of 're\.Pattern' objects\}|
|197|107554/59446|0\.02|0\.000|0\.024|0\.000|encoder\.py:333\(\_iterencode\_dict\)|
|479|2925|0\.018|0\.000|0\.018|0\.000|\{built-in method posix\.stat\}|
|394|829|0\.01|0\.000|0\.017|0\.000|style\.py:474\(to\_style\_proto\)|
|198|59446|0\.009|0\.000|0\.034|0\.000|encoder\.py:413\(\_iterencode\)|
|209|965|0\.008|0\.000|0\.088|0\.000|helper\.py:190\(create\_component\)|
|267|3961/1794|0\.008|0\.000|0\.020|0\.000|json\_format\.py:212\(\_RegularMessageToJsonObject\)|
|195|1851|0\.007|0\.000|0\.009|0\.000|encoder\.py:204\(iterencode\)|
|547|917|0\.007|0\.000|0\.007|0\.000|\{method 'sub' of 're\.Pattern' objects\}|
|194|1851|0\.006|0\.000|0\.050|0\.000|encoder\.py:182\(encode\)|
|467|126959|0\.006|0\.000|0\.006|0\.000|\{built-in method builtins\.isinstance\}|
|223|772/4|0\.005|0\.000|0\.006|0\.001|helper\.py:440\(diff\_component\)|
|544|3241|0\.004|0\.000|0\.004|0\.000|\{method 'split' of 'str' objects\}|
|487|3961|0\.004|0\.000|0\.004|0\.000|\{method 'ListFields' of 'google\.\_upb\.\_message\.Message' objects\}|
|266|3961/1794|0\.004|0\.000|0\.022|0\.000|json\_format\.py:201\(\_MessageToJsonObject\)|

The good news is that your diffing @richard-to seems relatively fast compared to everything else :)

Some things to look at:
- The `time.sleep` looks like the biggest culprit: https://github.com/google/mesop/blob/8b96c61ace9beef93f7e01e5d1473f146427f6ee/mesop/labs/chat.py#L186 - I think this was done because scrolll_into_view was happening too soon, but there's probably a better way of handling this. For example, maybe we can wrap [scrollIntoView](https://github.com/google/mesop/blob/8b96c61ace9beef93f7e01e5d1473f146427f6ee/mesop/web/src/shell/shell.ts#L114) with `setTimeout(..., 0)`
- The python-markdown library is taking a good chunk of time, but this seems expected because the markdown was getting quite sizable during this stress testing.
- A bunch of smaller overheads from serializing with JSON, protos, etc which all seem expected

@richard-to how slow was it getting for you? Even in my stress test, the network response was ~500ms even when there was a bunch of chat messages (albeit this is running locally with a macbook air M2).

**Comment by richard-to** [comment]
For me, it just progressively gets slower as more messages get added. So in this case, after about 57 messages, I'm at almost 700ms.

<img width="723" alt="Screenshot 2024-07-12 at 2 00 26 PM" src="https://github.com/user-attachments/assets/5c51ddf9-ae5a-41eb-a0dc-ac8962eb4bac">

**Comment by richard-to** [comment]
Yeah, I saw the scroll into view thing as well. I have a version where I removed the scroll into view which is actually what you're seeing in the above screenshot. 

But the problem is there's something that continues to get slower as more messages are added. Something in run path is my best guess since it was the only call where I was seeing a noticeable increase after multiple calls.

I took a glance at the function, but not immediately obvious why it would get slower and slower.

**Comment by wwwillchen** [comment]
It makes sense to me why it's steadily getting longer with each new message.

Essentially you're building a bigger component tree in the server, even though the component tree diff size is the same, so you'll spend more time constructing the tree, doing the diff, etc.

In particular, if you look at the second-highest entry: [treeprocessors.py:253](https://github.com/Python-Markdown/markdown/blob/33359faa385f59b84cd87df5f4b0996055a482e2/markdown/treeprocessors.py#L253) it looks like the hot path of the Python Markdown library that's turning strings into the markdown AST (I looked at this quickly, so verify what I'm saying :))

If you think about it, it's pretty wasteful because we know that all of the markdown calls except for the last one will eventually be diff'ed away.

A list of ideas from easy to hard (I'm not sure if we should actually do any of them, but just brainstorming):

- Cache the [call](https://github.com/google/mesop/blob/eb50c9ac3ce22aa233ecf189962322e3d43bf16d/mesop/components/markdown/markdown.py#L28) to the markdown library - pretty much use an LRU cache like I did in #614, but this will definitely take more memory so it's not super clear how big the cache size should be
- Cache the [call](https://github.com/google/mesop/blob/eb50c9ac3ce22aa233ecf189962322e3d43bf16d/mesop/components/markdown/markdown.py#L13) to the mesop component - we could cache the result of `me.markdown` or pretty much any built-in mesop component. It's a little trickier though because me.markdown does not actually return a value, so you'd need to essentially cache the constructed proto and then re-insert it.
- Cache pure user component - one idea that's floated in the back of my head is that we could do something like React's [pure component](https://react.dev/reference/react/PureComponent#skipping-unnecessary-re-renders-for-class-components). If a user component doesn't do any reads from state (or read mutable global state), and the args are immutable, then you can cache the value. This is quite restrictive (like React), but it makes it possible for app developers to do quite a bit of optimizations on their side.
  - There's an even more complicated way to do this where you can allow user components which read from state and detect which state properties are read from the user component and use those state properties as implicit keys for the cache. 

One thing that I've been thinking about is that we do quite a bit of duplicate-work between the first and second render loops to do the tree diff, so doing some kind of cache even with a small size limit could be quite beneficial.

**Comment by richard-to** [comment]
Yes, I agree that it makes sense that as the number of components grows, the slower it will get. I think mainly it's just the pace of the growth is not great.

It seems this is mainly from Markdown you're saying? If we tried a test where we used a me.text, do you think the performance would be noticeably better after 50 or so messages?

I do remember that once I tried to print out 200 me.code blocks and it was really slow (I think you recently added a fix for the event handlers). So maybe there is something related to markdown rendering.

**Comment by richard-to** [comment]
I tested it out by replacing me.markdown with me.text. It still increases, but there's a definite improvement there. After 50 requests, I got to about 200ms. Whereas with markdown I'm already near 700ms by 50 requests.

One thing I was wondering is if we could offload the markdown rendering to the javascript side. Seems like that could potentially solve the markdown rendering slowness, but wouldn't be a general optimization for the component tree itself

--------

Your suggestions for general perf improvements sound very interesting. I'll have to look more at that part of the code, which I'm not familiar with in terms of what it's doing yet.

**Comment by lianggecm** [comment]
I'm experiencing this extremely bazar performance issue that could be related to this. Let's say I create two practically identical apps, one is in main.py (page path "/") and the other one is in test_chat_import.py (page path "/test_chat"). I then start both apps with "mesop main.py". Here's the code for the main.py:

```
import mesop as me
import mesop.labs as mel
from test_chat_import import chat as test_chat
import time
@me.page(path="/")
def chat():
  mel.chat(transform)

LINES = ' '.join([
  "Mesop is a Python-based UI framework designed to simplify web UI development for engineers without frontend experience.",
  "It leverages the power of the Angular web framework and Angular Material components, allowing rapid construction of web demos and internal tools.",
  "With Mesop, developers can enjoy a fast build-edit-refresh loop thanks to its hot reload feature, making UI tweaks and component integration seamless.",
  "Deployment is straightforward, utilizing standard HTTP technologies.",
  "Mesop's component library aims for comprehensive Angular Material component coverage, enhancing UI flexibility and composability.",
  "It supports custom components for specific use cases, ensuring developers can extend its capabilities to fit their unique requirements.",
  "Mesop's roadmap includes expanding its component library and simplifying the onboarding processs.",
])


def transform(prompt: str, history: list[mel.ChatMessage]) -> str:
  start_time = time.time()
  yield '\n'+'Start time:'+str(start_time)+'\n'

  for i in range(5):
    yield '\n'
    for each in LINES.split(' '):
        time.sleep(0.002)
        yield each + "\n"



  end_time = time.time()
  yield '\n'+'End time:'+str(end_time)
  yield '\n\n Duration '+str(end_time - start_time)
```
The test_chat_import.py is practically identical with the only change being the "@me.page(path='/test_chat')" line. Here's the time it takes for each chat interaction in the "/" path (blue color line) and "/test_chat" (brown color line). The main page response time grows extremely fast while the imported test_chat path doesn't change much.
![image](https://github.com/user-attachments/assets/a4d5de95-f799-4f62-8b65-d42da087c765)


Not sure this is reproduceable on your end but if you can it might help you to identify the bug.

**Comment by richard-to** [comment]
Wow, yeah, that's really bizarre. I'll try to see if I can repro on my side when I get the chance. Thanks for posting this.

**Comment by richard-to** [comment]
I tested out replacing me.markdown with the markdown web component here (https://github.com/google/mesop/pull/667). This web component renders the markdown in the frontend. So avoids the server-side reprocessing hit we were getting with me.markdown.

The app still gets slower as more messages are added, but the rate of growth is slower.

After 50 requests (disabled sleep in the transform function and disabled scrolling) and it gets to 200ms. Previously with the same configuration, after 50 requests I was up to almost 700ms.

<img width="704" alt="Screenshot 2024-07-26 at 4 33 59 PM" src="https://github.com/user-attachments/assets/50803785-6e10-4530-bfbc-42af79b9bc58">

**Comment by richard-to** [comment]
We're planning to update the markdown component to render using Javascript instead of on the server side. This should improve the performance noticeably for mel.chat. It will still get slow after a lot of messages, but should require more messages.

**Comment by richard-to** [comment]
Now that we've upgraded to frontend markdown rendering, this should improve the performance of mel.chat.
