### ISSUE TITLE
Allow Flask Configuration

### ISSUE THREAD

**Issue by tpcgold** [google/mesop#626]
**Is your feature request related to a problem? Please describe.**
I try to add a login via SSO to the APP but cannot do so

**Describe the solution you'd like**
Allow access to the FLASK config

**Describe alternatives you've considered**
Create a MESOP app and extend it with already existing FLASK extensions

**Additional context**
e.g. SSO example FLASK:
Create a MESOP app with the help of already existing FLASK extensions

Example code how it could work:
```import os
import time

from mesop import Flask
import mesop.labs as mel
from ms_identity_python.flask import Auth

me = Flask(__name__)
me.config["SESSION_TYPE"] = "filesystem"
auth = Auth(
    me,
    authority=AUTHORITY,
    client_id=CLIENT_ID,
    client_credential=CLIENT_SECRET,
    redirect_uri=REDIRECT_URI,
)


@me.page(path="/text_to_text", title="Text I/O Example")
@auth.login_required
def mesop_app():
    mel.text_to_text(
        upper_case_stream,
        title="Text I/O Example",
    )


def upper_case_stream(s: str):
    yield s.capitalize()
    time.sleep(0.5)
    yield "Done"```

**Comment by richard-to** [comment]
At the moment we do not provide access to Flask, because in the future we may move away from Flask. So adding Flask access could make it more difficult to migrate away from Flask.

One option that I think could work in your SSO case is if you ran the Flask App separately from the Mesop App. This means that you could need a reverse proxy, such as Nginx in front though. The reverse proxy would then route to the Flask app for login and the Mesop app based on the URLs.

The SSO login flow would go through the Flask app.

Then you'd need to add some kind of custom decorator or function to check auth in Mesop.

This adds a bit more extra work, so it's definitely not that convenient. But it would allow you to use any framework you wanted, Flask, FastAPI, Django.

The drawback is that this should work for the SSO case, but wouldn't work for most other extensions.

**Comment by tpcgold** [comment]
Ok, thanks for letting me know. 
Yeah in this case I'll go the GCP way. (Using AD as Identity Provider in Identity Platform and LB + IAP)
