### ISSUE TITLE
Style.__init__() got an unexpected keyword argument min_height

### ISSUE THREAD

**Issue by onemriganka** [google/mesop#656]
**Describe the bug**

![mesop](https://github.com/user-attachments/assets/4a9976f0-7ea8-466e-b4a7-24406c6703d1)

**To Reproduce**
1. follow the doc 
2. make an env like instructed in the doc (use Powershell)
3. make main.py file 
4. run mesop main.py

**Expected behavior**
 The webpage should correctly load

 

**Desktop System Info**

-  windows 11
-  brave
- Version [  v1.67.123 (Jun 25, 2024) ]

**Comment by richard-to** [comment]
Hi @onemriganka. Thanks for the catch. The min_height field was added very recently and it is not in Mesop 0.9.4. For now you, can remove the min_height field and I think it should work. I think the UI may look slightly off (I think the footer won't be at the bottom iirc). We'll try to push out a new release soon.

**Comment by dorianherle** [comment]
Same issue for me!

**Comment by dorianherle** [comment]
A workaround for now is to go back to a previosu version: 
pip install mesop==0.9.4

**Comment by wwwillchen** [comment]
@onemriganka - we've just released v0.9.5 which includes min_height.

@dorianherle - I'm not sure why you got the the error "Style.init() got an unexpected keyword argument 'min_height'" with that example, since it doesn't use min_height. Please try the latest version of Mesop: `pip install -U mesop` and see if you're still running into the issue.
