### ISSUE TITLE
AI Editor - Change history seems to be global even changed to different page

### ISSUE THREAD

**Issue by richard-to** [google/mesop#911]
Not sure if this is expected behavior or not. But when I click the history button I expect the history of changes to be related to the current page that I'm on.

However, once we get to multi-file changes, I'm wondering what would be appropriate interface.

**Comment by wwwillchen** [comment]
Yeah that's a good point and something I wondered about too. I think scoping this to the current page makes sense.

The multi-file one is tricky since it could affect multiple pages and then we'd need to understand the dependency graph across modules.

Perhaps as a middle ground, we could make this a filter so it by default shows the "current page" changes, but then shows you all page changes so when we support multi-file changes, you'll still be able to see changes that cut cross-pages. WDYT?
